//makes swing and AWT components available
import javax.swing.*;
import java.awt.*;
//the followign import statement allows event handling
import java.awt.event.*;
//addign implements ActionListener so that the class can respond to action
//events
public class JAction extends JFrame implements ActionListener
{
   //contains components of: a label, field, and button.
   JLabel label = new JLabel("Enter your name");
   JTextField field = new JTextField(12);
   JButton button = new JButton("OK");
   
   //set Jframe title, and close program when Jframe is closed
   //also set layout manager
   public JAction()
   {
      super("Action");
      setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      setLayout(new FlowLayout());
      add(label);
      add(field);
      add(button);
      //this registered JAction class as a listener for events
      //generated by either the button or the text field
      button.addActionListener(this);
      field.addActionListener(this);
   }
   //this method will change the text on both the label and the button
   //whenever the user clicks the button or presses Enter in the text field
   public void actionPerformed(ActionEvent e)
   {
      label.setText("Thank you");
      button.setText("Done");
   }
   //adding a main method so that i can instantiate a jaction object
   //for demonstration purposes
   public static void main(String[] args)
   {
      JAction aFrame = new JAction();
      final int WIDTH = 250;
      final int HEIGHT = 100;
      aFrame.setSize(WIDTH, HEIGHT);
      aFrame.setVisible(true);
   }
}